image:
  file: .gitpod.Dockerfile

tasks:
  - name: 🏎 Start Redis Server
    command: redis-server

  - name: 🪝 Setup hooks and run tests
    init: deno task prepare
    command: deno task test

ports:
  - port: 6379
    visibility: private
    onOpen: ignore
